apiVersion: v1
kind: ConfigMap
metadata:
  name: vpa-webhook-config
  namespace: kube-system
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    # "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
data:
  mutatingWebhookConfig: |-
    apiVersion: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    metadata:
      name: vpa-webhook-config
      labels:
        app.kubernetes.io/managed-by: aks
    webhooks:
    - admissionReviewVersions:
      - v1
      clientConfig:
        service:
          name: vpa-webhook
          namespace: kube-system
          port: 443
      failurePolicy: Ignore
      matchPolicy: Equivalent
      name: vpa.k8s.io
      sideEffects: None
      timeoutSeconds: 3
      rules:
      - apiGroups:
        - ""
        apiVersions:
        - v1
        operations:
        - CREATE
        resources:
        - pods
        scope: '*'
      - apiGroups:
        - autoscaling.k8s.io
        apiVersions:
        - '*'
        operations:
        - CREATE
        - UPDATE
        resources:
        - verticalpodautoscalers
        scope: '*'
