---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpa-recommender
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vpa-recommender
  template:
    metadata:
      labels:
        app: vpa-recommender
    spec:
      serviceAccountName: vpa-recommender
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534 # nobody
      containers:
      - name: recommender
        image: k8s.gcr.io/autoscaling/vpa-recommender:0.13.0
        imagePullPolicy: Always
        startupProbe:
          httpGet:
            path: /health-check
            port: 8942
            scheme: HTTP
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /health-check
            port: 8942
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8942
            scheme: HTTP
# {{- $currentDeployment := (lookup "apps/v1" "Deployment" "kube-system" "vpa-recommender") }}
# {{- if (not $currentDeployment) }}
        resources:
          limits:
            cpu: 200m
            memory: 1000Mi
          requests:
            cpu: 50m
            memory: 500Mi
# {{- else }}
# {{- $container := index $currentDeployment.spec.template.spec.containers 0 }}
# {{- $resource := $container.resources }}
#         resources:
#           {{- toYaml $resource | nindent 10 }}
# {{- end }}
        ports:
        - name: prometheus
          containerPort: 8942
