name: Test Coverage Check

on:
  pull_request:
    branches:
      - main  # Adjust to your target branch
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag to publish images, defaults to the latest one'
        type: string

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: '1.x'  # Adjust based on your project requirements

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y bc

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
          grep -v -e "/mock_" -e "main.go" -e "/toolkit/log/" -e "/toolkit/certificates/certoperator/" coverage.out > filtered_coverage.out
          go tool cover -func=filtered_coverage.out | tail -n 1 | awk '{print $3}' | sed 's/%//' > coverage.txt

      - name: Fail if coverage is below threshold
        id: check_coverage
        run: |
          COVERAGE=$(cat coverage.txt)
          echo "Total Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
            echo "Test coverage ($COVERAGE%) is below the required threshold (80%)"
            exit 1
          fi

      - name: Upload coverage report (optional)
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 #v4.6.1
        with:
          name: filtered-coverage
          path: filtered_coverage.out
